set nu
set nocompatible
filetype indent plugin on
syntax on
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set nostartofline
set ruler
set laststatus=2
set visualbell
set mouse=a
set cmdheight=2
set pastetoggle=<F11>
set shiftwidth=4
set softtabstop=4
set expandtab
